### PR TITLE
ci: add diff_check workflow

### PR DESCRIPTION
**Pull request by burntcarrot**
Added a generate diff check. Related #525.

### CODE REVIEW

**Comment by burntcarrot** [comment]
My guess is that I've not added the relative paths to each Makefile for each service, since you have to be in a directory which contains a Makefile. 

For example, the paths should be pointing to their respective services like `/home/runner/work/go-storage/go-storage/go-service-azblob` and not `/home/runner/work/go-storage/go-storage`.

**Comment by Xuanwo** [comment]
We need to add a `diff_check.yml` under https://github.com/beyondstorage/go-service-s3/tree/master/.github/workflows like what we do for `gofmt.yml`. So we can run the check every time there is a new push or PR for `go-service-s3`.

**Comment by burntcarrot** [comment]
> Sorry, I think we had some communication problems. I'm sorry I didn't read your example carefully in #525. We need to add `diff_check` for every single service instead of in `go-storage`. (So that we can check the diff while there are new push / PRs for services)

I was suspecting this earlier. Since `generated.go` lies in the repos of each service, hence, the actions should be run there.

Anyways, thanks for clarifying now! I'll make PRs for each service.

**Comment by Xuanwo** [comment]
Closed as discussed in https://github.com/beyondstorage/go-storage/pull/664#issuecomment-879692592

**Pull request closed without merging**
