### PR TITLE
fix: Correction of CreateLink description error

### PR DESCRIPTION
**Pull request by abyss-w**
fix: Correction of CreateLink description error

### CODE REVIEW

**Comment by Xuanwo** [comment]
Hi, please refer to https://beyondstorage.io/docs/general/contributor-guide#create-your-branch to avoid extra commits in PR.

**Comment by abyss-w** [comment]
> Hi, please refer to https://beyondstorage.io/docs/general/contributor-guide#create-your-branch to avoid extra commits in PR.

Okay!

**Comment by abyss-w** [comment]
ping @Xuanwo , Do I need to merge these extra commits? But then it will do a forced push.

**Comment by Xuanwo** [comment]
Instead of working on `master` branch, we prefer to create new branches every time.

So we have to do the following things (If you set the upstream correctly as described in [contributor-guide](https://beyondstorage.io/docs/general/contributor-guide))

```shell
# Backup your work
git reset HEAD~1 && git stash
# Fetch upstream changes
git fetch upstream
# Reset your branch to upstream master (Danguouse step, make sure you on the right branch)
git reset --hard upstream/master
# Set your master branch to upstream/master so that we can use git pull directly later
git branch --set-upstream-to upstream/master
# Create a new branch based on upstream/master
git checkout -b "issue-xxx"
# Reapply your work
git stash apply
```

And then we can send PRs.

For further works, we can simply do:

```shell
# Swtich to the master branch
git checkout master
# Pull changes from upstream
git pull
# Create and switch to new branches
git checkout -b "issue-xxx"
# Start your work!
```

**Comment by abyss-w** [comment]
> Instead of working on `master` branch, we prefer to create new branches every time.
> 
> So we have to do the following things (If you set the upstream correctly as described in [contributor-guide](https://beyondstorage.io/docs/general/contributor-guide))


Got it!

**Comment by Xuanwo** [comment]
@abyss-w , Hi, any progress on this issue?

**Comment by abyss-w** [comment]
> @abyss-w , Hi, any progress on this issue?

I've done the first part of what you listed, do I need to recommit now?

**Comment by Xuanwo** [comment]
> I've done the first part of what you listed, do I need to recommit now?

Yes, please close this PR and create a new PR based on your new branch.

**Comment by abyss-w** [comment]
> Yes, please close this PR and create a new PR based on your new branch.

Got it!

**Pull request closed without merging**
