### PR TITLE
definitions: Add support for type uint64

### PR DESCRIPTION
**Pull request by zu1k**
https://github.com/beyondstorage/go-service-ipfs/pull/3#commitcomment-53044856

### CODE REVIEW

**Comment by Xuanwo** [comment]
Looks like we need a `go fmt` here?

**Comment by Xuanwo** [comment]
Nice!

**Comment by zu1k** [comment]
My golang automatically adds a line: `//go:build tools`.

And it looks like there are a lot of files that need to be formatted.

**Comment by Xuanwo** [comment]
> And it looks like there are a lot of files that need to be formatted.

We will support go 1.17 after it officially released. So doesn't matter, running `make build` to make sure all files formatted is OK to me.

**Comment by xxchan** [comment]
Can you also add it here https://github.com/beyondstorage/go-storage/blob/master/services/new.go#L197-L202

**Review by Xuanwo — APPROVED** [review]

**Pull request merged**
