### PR TITLE
When migrate to Factory init, make build failed

### PR DESCRIPTION
**Pull request by Joey2132**
When migrate to Factory init, make build failed with  err:
```
2021/11/19 10:56:25 not handled type &ast.FuncType{Func:1884, Params:(*ast.FieldList)(0xc0002be0f0), Results:(*ast.FieldList)(0xc0002be120)}
```

And I just don't know what happend.

### CODE REVIEW

**Comment by Xuanwo** [comment]
But the build is passed?

**Comment by Joey2132** [comment]
> But the build is passed?

The generate operation failed. So we don't support all operation. All of them just skipped.

**Comment by Xuanwo** [comment]
Oh, I got it.

> 2021/11/19 03:02:14 not handled type &ast.FuncType{Func:1884, Params:(*ast.FieldList)(0xc000209500), Results:(*ast.FieldList)(0xc000209560)}

We didn't exit the build with error code, so the build is not break.

**Comment by Joey2132** [comment]
And without useful information, I don't realize what causes it.

**Comment by Xuanwo** [comment]
Please create an issue which refer this PR, let's fix it.

**Comment by Joey2132** [comment]
> Please create an issue which refer this PR, let's fix it.

Got it.

**Pull request closed without merging**
