### PR TITLE
fix: added gofmt to action

### LINKED ISSUE #563: Add gofmt check in workflows
We need to add `gofmt` check to make sure every PR has been formatted.

Like https://github.com/digitalocean/godo/pull/396/files

We should add  the following action `.github/workflows/gofmt.yml` in every golang related repos:

```yaml
name: "gofmt"

on: [ push,pull_request ]

jobs:
  gofmt:
    name: gofmt
    runs-on: ubuntu-latest

    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: "1.15"

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Format
        run: if [ "$(gofmt -l . | wc -l)" -gt 0 ]; then exit 1; fi
```

Tips:
- Should be `make build`, as `make build` will format all code.

## Todo Lists

- [x] https://github.com/beyondstorage/go-storage/pull/660
- [x] https://github.com/beyondstorage/go-service-ipfs/pull/8
- [x] https://github.com/beyondstorage/go-coreutils/pull/9
- [x] https://github.com/beyondstorage/go-service-azblob/pull/33
- [x] https://github.com/beyondstorage/go-service-cos/pull/37
- [x] https://github.com/beyondstorage/go-service-dropbox/pull/26
- [x] https://github.com/beyondstorage/go-service-fs/pull/50
- [x] https://github.com/beyondstorage/go-service-gcs/pull/41
- [x] https://github.com/beyondstorage/go-service-kodo/pull/34
- [x] https://github.com/beyondstorage/go-service-oss/pull/35
- [x] https://github.com/beyondstorage/go-service-qingstor/pull/62
- [x] https://github.com/beyondstorage/go-service-s3/pull/140
- [x] https://github.com/beyondstorage/go-service-uss/pull/14
- [x] https://github.com/beyondstorage/go-service-example/pull/8

### PR DESCRIPTION
**Pull request by burntcarrot**
Related #563.

Added `gofmt` check to make sure every PR has been formatted.

### CODE REVIEW

**Comment by xxchan** [comment]
Oops. It turns out that some files are not formatted via `make build`! 

```bash
❯ gofmt -l .
cmd/definitions/bindata/bindata.go
cmd/definitions/parse.go
cmd/definitions/tools.go
cmd/definitions/type.go

❯ go fmt -n ./...  
/usr/local/go/bin/gofmt -l -w pkg/credential/credential.go
/usr/local/go/bin/gofmt -l -w cmd/definitions/tests/storage.go
/usr/local/go/bin/gofmt -l -w pkg/credential/error.go
/usr/local/go/bin/gofmt -l -w pkg/fswrap/doc.go
/usr/local/go/bin/gofmt -l -w pkg/fswrap/fileinfo.go
/usr/local/go/bin/gofmt -l -w pkg/fswrap/httpfs.go
/usr/local/go/bin/gofmt -l -w pkg/fswrap/iofs.go
/usr/local/go/bin/gofmt -l -w pairs/generated.go
/usr/local/go/bin/gofmt -l -w pkg/headers/range.go
/usr/local/go/bin/gofmt -l -w pkg/httpclient/client.go
/usr/local/go/bin/gofmt -l -w pkg/httpclient/conn.go
/usr/local/go/bin/gofmt -l -w pkg/httpclient/dialer.go
/usr/local/go/bin/gofmt -l -w pairs/error.go
/usr/local/go/bin/gofmt -l -w cmd/definitions/tests/generated.go
/usr/local/go/bin/gofmt -l -w pkg/iowrap/mock_test.go
/usr/local/go/bin/gofmt -l -w pkg/iowrap/pipe.go
/usr/local/go/bin/gofmt -l -w pkg/iowrap/interface.go
/usr/local/go/bin/gofmt -l -w cmd/definitions/tests/doc.go
/usr/local/go/bin/gofmt -l -w pkg/iowrap/pipe_test.go
/usr/local/go/bin/gofmt -l -w pkg/iowrap/reader.go
/usr/local/go/bin/gofmt -l -w pkg/iowrap/doc.go
/usr/local/go/bin/gofmt -l -w pairs/doc.go
/usr/local/go/bin/gofmt -l -w pkg/iowrap/writer_test.go
/usr/local/go/bin/gofmt -l -w pkg/randbytes/randbytes.go
/usr/local/go/bin/gofmt -l -w doc.go
/usr/local/go/bin/gofmt -l -w services/error.go
/usr/local/go/bin/gofmt -l -w services/new.go
/usr/local/go/bin/gofmt -l -w types/doc.go
/usr/local/go/bin/gofmt -l -w types/error.go
/usr/local/go/bin/gofmt -l -w types/info.generated.go
/usr/local/go/bin/gofmt -l -w types/info.go
/usr/local/go/bin/gofmt -l -w types/interceptor.go
/usr/local/go/bin/gofmt -l -w types/iterator.generated.go
/usr/local/go/bin/gofmt -l -w pkg/iowrap/pipe_bench_test.go
/usr/local/go/bin/gofmt -l -w types/object.generated.go
/usr/local/go/bin/gofmt -l -w types/object.go
/usr/local/go/bin/gofmt -l -w cmd/definitions/tests/connstr_test.go
/usr/local/go/bin/gofmt -l -w cmd/definitions/tests/service.go
/usr/local/go/bin/gofmt -l -w types/pair.go
/usr/local/go/bin/gofmt -l -w types/object_test.go
/usr/local/go/bin/gofmt -l -w types/iterator.go
/usr/local/go/bin/gofmt -l -w pkg/headers/headers.go
/usr/local/go/bin/gofmt -l -w pkg/credential/credential_test.go
/usr/local/go/bin/gofmt -l -w pkg/randbytes/randbytes_test.go
/usr/local/go/bin/gofmt -l -w cmd/definitions/tests/utils.go
/usr/local/go/bin/gofmt -l -w docs/rfcs/1/main_test.go
/usr/local/go/bin/gofmt -l -w pkg/iowrap/writer.go
/usr/local/go/bin/gofmt -l -w types/operation.go
/usr/local/go/bin/gofmt -l -w pkg/iowrap/reader_test.go
/usr/local/go/bin/gofmt -l -w types/operation.generated.go
```

Why only `cmd/definitions/tests` are formatted instead of `cmd/definitions`?

**Comment by Xuanwo** [comment]
`go fmt ./...` == `gofmt -l -w`, but without `-s` which means simplify code.

I prefer to use `go fmt ./..` here.

**Comment by Xuanwo** [comment]
> Oops. It turns out that some files are not formatted via `make build`!

I think it's affected by the package's tag. (definitions are under `tools` tag), and `gofmt` doesn't care about the package tag.

Maybe use `gofmt` is a good choice.

**Comment by Xuanwo** [comment]
How about moving the format check in a separate action called `gofmt` instead of in `unittests`? In the new action, we can only run it in Linux instead of adding extra `if` statement.

**Comment by burntcarrot** [comment]
I was thinking about the same. Should I go on and create a new action for `gofmt`?

It would make the workflow much more cleaner and easier to maintain.

**Comment by Xuanwo** [comment]
> I was thinking about the same. Should I go on and create a new action for `gofmt`?
> 
> It would make the workflow much more cleaner and easier to maintain.

So nice!

I have updated https://github.com/beyondstorage/go-storage/issues/563 and please take a look.

**Comment by Xuanwo** [comment]
I will create a pr to fix the code format.

**Comment by Xuanwo** [comment]
Can you merge the master branch so that we can get the CI passed?

**Review by Xuanwo — APPROVED** [review]

**Comment by Xuanwo** [comment]
Thanks for your contribution! :laughing:

**Pull request merged**
